### ISSUE TITLE
Duplicate Data: Chun-Li has the same light combo repeated twice in Combos/Light Confirms

### ISSUE THREAD

**Issue by jmarkman** [D4RKONION/FAT#19]
Low priority (whenever you can get around to it):

On Chun-Li's combo page, she has the same light confirm combo listed twice: cr.lp > st.lp > st.lp xx light legs. One entry has a comment and one doesn't, which differentiates them. If a user clicks the first instance of that light confirm combo, FAT will highlight both of them:

![firefox_2021-03-14_20-36-01](https://user-images.githubusercontent.com/8032019/111090195-4f7f3700-8505-11eb-8365-037381015620.png)

Had to find where it was by looking in `Combos.ts` and extracting the JSON to its own file, but if the JSON is formatted, the one with the comment is at line 3589, the one without is at line 3607:

![Code_2021-03-14_20-33-41](https://user-images.githubusercontent.com/8032019/111090281-98cf8680-8505-11eb-9450-9ea74775974e.png)

**Comment by D4RKONION** [comment]
The combo sheet is maintained via spreadsheet, I should note this in the readme

**Comment by D4RKONION** [comment]
Fixed in 0135016, and added a section to the README
