### ISSUE TITLE
Feature to add move list as gif next to the frame data

### ISSUE THREAD

**Issue by koeliga** [D4RKONION/FAT#49]
When you know a certain is move is minus and don't know what the move looks like you need to look it up but if a gif is added next to the move this would resolve this issue. Would be a great feature imo

**Comment by D4RKONION** [comment]
Hey, thanks for the suggestion! Sadly due to storage issues, the immense amount of work invovled but mainly the copyright issues, there's no way for this to be added. Sorry!
