### ISSUE TITLE
Using SFV JSON on another project

### ISSUE THREAD

**Issue by p-Jimenez** [D4RKONION/FAT#50]
Is it allowed to use the SFV JSON on another project? I built an open source Discord bot with this JSON data (of course linking to this repo). Tried to used this one ([https://github.com/D4RKONION/fatsfvframedatajson](https://github.com/D4RKONION/fatsfvframedatajson)) but it is outdated.

Thanks in advanced!

**Comment by D4RKONION** [comment]
Yes, as long as you follow the license of FAT that's no problem. Link me when you're done would love to take a look!

https://github.com/D4RKONION/FAT#reusing-fat-source-code

**Comment by p-Jimenez** [comment]
Been doing a lot of recent changes and code is really rough rn (started the project almost a year ago and I've improved so much as a developer) but here is the repo:  [https://github.com/p-Jimenez/discord-aegis-helper](https://github.com/p-Jimenez/discord-aegis-helper)

If you want to test it I got it running on a server (URL permissions set to admin because I was too lazy to figure it out, gonna change that tomorrow ASAP) [https://discord.com/api/oauth2/authorize?client_id=900794699328155680&permissions=8&scope=bot%20applications.commands](https://discord.com/api/oauth2/authorize?client_id=900794699328155680&permissions=8&scope=bot%20applications.commands)
