### ISSUE TITLE
Bug when switching from Link to Cancel

### ISSUE THREAD

**Issue by SparklySkittles** [D4RKONION/FAT#78]
this bug black screens (or white screens depending on the theme) when switching from Link to Cancel in the Frame Trap Checker calculator if the first move is set and the second move isnt, depending on what move. at first i thought it was dependent on the length of the move but after a bit more testing that doesn't seem to be the case. 

Moves that i tested in move 1 and was able to recreate the bug:
- GGST Pot Hammerfall
- GGST Pot Rocketman
- SF6 A.K.I. Super Art Lvl 3

I have a Samsung phone, however I tested it on my friend's iphone and it worked the same way, so from what i can tell its not platform specific

if you need any more information let me know!

**Comment by D4RKONION** [comment]
Fixed in dc3a05162fb1c233416ea881e9b95f319e258bd8, thank you for the report
